defaults:
  - _self_
  - _shared_setting

name: preference
pre_train_steps: 2
stepwise_steps: 1
K: 2

reward_config:
  logging_steps: 1
  log_level: debug
  learning_rate: 1e-4
  max_length: 72
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  report_to: wandb