defaults:
  - _self_
  - rlhf: bap
  - attack: pite

data_split: 'tcr'
augment_rounds: 4
# output_dir: ${eval:"'${hydra:runtime.output_dir}'.replace('${hydra:runtime.cwd}', '')[:-1]"}
output_dir: ${hydra:runtime.output_dir}
base_dir: ${hydra:runtime.cwd}

project_name: BAP enhancement with RHLF
run_name: ${attack.name}-${rlhf.name}